spring:
  datasource:
    url: jdbc:${CLEARDB_CHARCOAL_URL:mysql://localhost:3306/heroku_829dec9982ec23c}
    username: search_engine
    password: testtest
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
server:
  port: ${PORT:8080}
custom:
  sites:
    - url: https://ErrorTest.ru
      name: ErrorTest
    - url: https://www.poelab.com
      name: PoeLab
    - url: https://skillbox.ru
      name: Skillbox
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
  referrer: https://www.google.com