spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: search_engine
    password: testtest
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
custom:
  sites:
    - url: https://blablablabla.ru
      name: Bla
    - url: https://ru.wix.com
      name: Wix
    - url: https://skillbox.ru
      name: Skillbox
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
  referrer: https://www.google.com